FROM python:3.11.7
COPY ./backend /var/www/meetell.ru/backend
WORKDIR /var/www/meetell.ru/backend
COPY ./backend /var/www/meetell.ru/backend
WORKDIR /var/www/meetell.ru/backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install -r requirements.txt
RUN python manage.py makemigrations
RUN python manage.py migrate
RUN python manage.py loaddata data.json