version: '3.7'

services:
  backend:
    build: 
      context: .
      dockerfile: docker/python/DockerFile
    container_name: backend
    command: gunicorn backend_settings.wsgi:application --bind 0.0.0.0:8000 -w 2
    expose:
      - 8000
    restart: unless-stopped
    depends_on:
      - pgdb

  frontend:
    build: 
      context: .
      dockerfile: docker/react/DockerFile
    restart: unless-stopped
    expose:
      - 3000
    command: serve -s /var/www/meetell.ru/frontend/build -l 3000
    depends_on:
      - backend

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - /etc/letsencrypt/live/meetell.ru/fullchain.pem:/etc/nginx/cert.pem
      - /etc/letsencrypt/live/meetell.ru/privkey.pem:/etc/nginx/key.pem
    depends_on:
      - frontend

  bot:
    build: 
      context: .
      dockerfile: docker/python/DockerFile
    container_name: bot
    command: python3 manage.py bot
    restart: unless-stopped
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=meetell
      - POSTGRES_USER=postgres_meetell
      - POSTGRES_PASSWORD=meecv32tell
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null