# pull official base image
FROM node:20.12.2

COPY ./frontend/meetell_app /var/www/meetell.ru/frontend/
WORKDIR /var/www/meetell.ru/frontend/

COPY ./frontend/meetell_app/package.json /var/www/meetell.ru/frontend/
COPY ./frontend/meetell_app/package-lock.json /var/www/meetell.ru/frontend/

RUN npm install -g serve
RUN npm install

# copy react project
# COPY . .

# build react project
RUN npm run build
ENV HTTPS=true