# pull official base image
FROM node:20.12.2

COPY ./frontend/meetell_app /var/www/it-prod.pro/frontend/
WORKDIR /var/www/it-prod.pro/frontend/

COPY ./package.json .
COPY ./package-lock.json .

RUN npm install -g serve
RUN npm install

# copy react project
COPY . .

# build react project
RUN npm run build