# Generated by Django 5.0.6 on 2024-06-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripuser',
            name='state',
            field=models.CharField(choices=[('W', 'Waiting'), ('Q', 'Question'), ('N', 'No'), ('Y', 'Yes'), ('R', 'Rate'), ('E', 'End')], default='W', max_length=1),
        ),
    ]
