# Generated by Django 5.0.6 on 2024-07-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='map_block',
            field=models.TextField(default=None, null=True),
        ),
    ]
