# Generated by Django 5.0.6 on 2024-06-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetell', '0003_trip_chat_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='time_en',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='time_st',
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
