# Generated by Django 5.0.6 on 2024-06-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetell', '0005_alter_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripuser',
            name='rate_user',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
